---
title: "IUU_Index_Analysis"
author: "Chloe Swick"
date: "2023-12-21"
output: html_document
---

```{r setup, setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(dplyr)
library(janitor)
library(readxl)
```



# Loading engagment metrics per organization 

```{r}
organization_engagements <- read_csv("Skylight Program Metrics_Organizations_Table.csv")
```


# Loading engagement metrics per country 

```{r}
weekly_country_engagements <- read_csv("Skylight Program Metrics_Countries_Table.csv")
```



# Loading total engagements per country and organization 

```{r}
skylight_countries <- read_csv("Metrics_Countries_Pivot_table-2.csv")
```


# Loading IUU index indicator scores 2019-2023 

```{r}
indicator_scores <- read_csv("iuu_fishing_index_2019-2023_indicator_scores.csv")
```


# Loading Skylight deal dates 

```{r}
skylight_deals <- read_excel("Skylight Deals.xlsx")
```



# Cleaning data 


```{r}
skylight_deals <- clean_names(skylight_deals)
iuu_index_scores <- clean_names(indicator_scores)
organization_engagements <- clean_names(organization_engagements)
country_engagements_total <- clean_names(skylight_countries)
weekly_country_engagements <- clean_names(weekly_country_engagements)
```



# Compiling data 

join by country 

```{r}
colnames(country_engagements_total)[1] = "x"
```

```{r}
iuu_index_countries <- c(unique(iuu_index_scores$country))

view(iuu_index_scores)

skylight_countries <- c(unique(weekly_country_engagements$country))

view(skylight_countries)

```

```{r}
df3 <- country_engagements_total %>%
  filter(x %in% iuu_index_countries)
```



```{r}
matches <- grep(paste(iuu_index_countries, collapse = "|"), 
                skylight_countries, ignore.case = TRUE, value = TRUE)

view(matches)

#country_engagements$iuu_index_match <- ifelse(iuu_index_countries %in% matches, iuu_index_countries, NA)

```



```{r}

# Get unique values from both vectors
all_values <- unique(c(iuu_index_countries, skylight_countries))

# Create a data frame with NAs
common_countries_df <- data.frame(country = all_values, iuu_index_countries = NA, skylight_countries = NA)

# Fill in values in the data frame based on the presence in vectors
common_countries_df$iuu_index_countries[match(iuu_index_countries, common_countries_df$country)] <- iuu_index_countries
common_countries_df$skylight_countries[match(skylight_countries, common_countries_df$country)] <- skylight_countries

common_countries_df$treatment_yes_no <- ifelse(is.na(common_countries_df$skylight_countries), 0, 1)


# Print the result
#print(common_countries_df) ## good start but need to figure out a good way to get rid of the spelling differences (micronesia and south korea). maybe we can ask Chris
```


```{r}
#weekly_country_engagements$active_yes_no <- ifelse(weekly_country_engagements$no_of_active_weeks>4, 1, 0)
```



```{r}
dind_df <- iuu_index_scores %>% full_join(common_countries_df, by = join_by(country)) %>%
  full_join(weekly_country_engagements, by = join_by(country))
```


```{r}

ctk <- c("deal_title", "deal_country", "deal_deal_created", "deal_last_stage_change")

active_country_dates_df <- skylight_deals %>% 
  filter(deal_stage == "Engaged") %>% 
  subset(select = ctk)
# 35 countries as "engaged", but 45 countries in analytics data
```

```{r}
active_country_dates_df <- active_country_dates_df %>% 
  mutate(treatment_year = as.integer(format(as.Date(deal_deal_created), "%Y"))) 

dind_df_final <- dind_df %>% 
  left_join(active_country_dates_df %>% 
    select(deal_country, treatment_year), 
    by = c("skylight_countries" = "deal_country")) %>% 
  mutate(post_treatment = ifelse(is.na(treatment_year) | treatment_year <= year, 1, 0),
         post_treatment = ifelse(is.na(treatment_year), 0, post_treatment)) %>% 
  rename(skylight_treatment = treatment_yes_no)

### still want to add the number of sessions as a measure of engagement

```

```{r}
dind_df_5 <- dind_df_final %>% 
  filter(indicator_id == 5)

```


# Data Visualizations
```{r}
ggplot(dind_df_final, aes(x = year, y = score, color = skylight_treatment, group = interaction(indicator_id, skylight_treatment))) +
  stat_summary(fun = "mean", geom = "line", size = 1) +
  labs(title = "Mean Score Over Years by Skylight Treatment",
       x = "Year",
       y = "Mean Score",
       color = "Skylight Treatment") +
  facet_wrap(~ indicator_id, scales = "free_y") +
  theme_minimal()
```




```{r}
mexico_rows <- engagements_table %>%
  filter(grepl("mexico", tolower(Engagement)))
```




