---
title: "clean and prep subset data"
author: "E.M.Thomas"
date: "2024-03-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(janitor)
library(readxl)
library(countrycode)
library(broom)
library(here)
library(tidyr)
library(jtools)
library(caret)
library(AICcmodavg) 
library(equatiomatic)
library(zoo)

```

# Load and clean data
```{r}
# filter year for indexs
filter_year <- 2019 #to update across all dataframes 
```



### Skylight data
```{r}
### Organization engagements
organization_engagements <- read_csv(here("data", "Skylight Program Metrics_Organizations_Table.csv")) %>% clean_names()

### Weekly country engagements
weekly_country_engagements <- read_csv(here("data", "Skylight Program Metrics_Countries_Table.csv")) %>% clean_names()

weekly_country_engagements$country <- countrycode(weekly_country_engagements$country, "country.name", "country.name") 

weekly_country_engagements <- weekly_country_engagements%>% 
  filter(no_of_active_weeks >2) 

#list of active skylight countries 
active_skylight_countries <- weekly_country_engagements$country 

### Engagment sessions
skylight_engagement_sessions <- read_csv(here("data","Metrics_Countries_Pivot_table-2.csv")) %>% clean_names()

country_sessions <- skylight_engagement_sessions %>% 
  rename(country = engagement)

country_sessions$country <- countrycode(country_sessions$country, "country.name", "country.name") 

country_sessions <- country_sessions %>% 
  drop_na(country) %>% 
  group_by(country) %>%
  summarize(sessions = sum(sessions, na.rm = TRUE))

### Deals data
skylight_deal_dates <- read_excel(here("data", "updated deals.xlsx")) %>% clean_names()

skylight_deal_dates$deal_country[skylight_deal_dates$deal_country == "Micronesia"] <- "Federated States of Micronesia"

skylight_deal_dates$country <- countrycode(skylight_deal_dates$deal_country, "country.name", "country.name")
```


# IUUFR Data
```{r}
# Read in and clean the IUUFR data
iuu_index_scores <- read_csv(here("data", "iuu_fishing_index_2019-2023_indicator_scores.csv")) %>% 
                clean_names() 
                
iuu_index_scores$country[iuu_index_scores$country == "Micronesia (FS of)"] <- "Federated States of Micronesia"
iuu_index_scores$country <- countrycode(iuu_index_scores$country, "country.name", "country.name") 
iuu_index_countries <- c(unique(iuu_index_scores$country))


# Make each indicator a separate column 
iuufr_index_wide <- iuu_index_scores %>% 
  select(country, year, indicator_name, score) %>% 
  pivot_wider(names_from = "indicator_name", 
             values_from = "score") %>% 
  clean_names() %>% 
  group_by(country) %>%
  fill(everything()) %>%  # Fill missing values within each country group
  slice(n()) %>%  # Keep only the last observation within each country group
  ungroup() %>%
  select(-year) 

iuufr_na_counts <- as.data.frame(colSums(is.na(iuufr_index_wide))) %>% 
  rename(na_counts = 1) %>% 
  filter(na_counts < 15)

#Finalize iuufr data set, clean up some NAs, select interesting indicators
iuufr_index_final <- iuufr_index_wide %>%
  select(country,
         vessels_on_iuu_lists,
         views_of_mcs_practitioners_on_coastal_compliance_incidents,
         ratification_accession_of_unclos_convention,
         provision_of_vessel_data_for_inclusion_in_global_record,
         designated_ports_specified_for_entry_by_foreign_vessels,
         size_of_eez,
         dependency_on_fish_for_protein,
         party_to_the_psma,
         trade_balance_for_fisheries_products) 


```


```{r}
### Governance indicators
# Read in and clean data
governance_indicators <- read_csv(here("data", "governance_indicators.csv")) %>% 
  clean_names() %>%
  rename_all(~ gsub("x(\\d+)_yr\\1", "\\1", .)) %>% 
  rename(country=country_name)

governance_indicators$country <- countrycode(governance_indicators$country,"country.name", "country.name")

# Extract the indicator estimates 
gov_id_estimates <- governance_indicators %>% 
  filter(grepl("EST", series_code)) %>% 
  mutate_all(~ ifelse(. == "..", NA, .)) 

# Put all the indicators in separate columns 
wb_gov_index_df <- gov_id_estimates %>%
  pivot_longer(cols = 5:28,
               names_to = "year", 
               values_to = "value") %>% 
  subset(select = -series_code) %>% 
  pivot_wider(names_from = "series_name",
              values_from = "value") %>% 
  clean_names() %>% 
  filter(country %in% iuu_index_countries) %>% 
  select(-country_code) %>% 
  #select(country, year, voice_and_accountability_estimate, control_of_corruption_estimate) 
  group_by(country) %>%
  fill(everything()) %>%  # Fill missing values within each country group
  slice(n()) %>%  # Keep only the last observation within each country group
  ungroup() %>%
  select(-year)

wb_gov_na_counts <- as.data.frame(colSums(is.na(wb_gov_index_df))) %>% 
  rename(na_counts = 1) %>% 
  filter(na_counts < 15)

# Convert indicator scores to numeric
wb_gov_index_df$control_of_corruption_estimate <- as.numeric(wb_gov_index_df$control_of_corruption_estimate)
wb_gov_index_df$government_effectiveness_estimate <- as.numeric(wb_gov_index_df$government_effectiveness_estimate)
wb_gov_index_df$political_stability_and_absence_of_violence_terrorism_estimate <- as.numeric(wb_gov_index_df$political_stability_and_absence_of_violence_terrorism_estimate)
wb_gov_index_df$regulatory_quality_estimate <- as.numeric(wb_gov_index_df$regulatory_quality_estimate)
wb_gov_index_df$rule_of_law_estimate <- as.numeric(wb_gov_index_df$rule_of_law_estimate)
wb_gov_index_df$voice_and_accountability_estimate <- as.numeric(wb_gov_index_df$voice_and_accountability_estimate)


wb_gov_index_final <- wb_gov_index_df 

```


```{r}
### GDP per capita
wb_gdp_pc <- read_csv(here("data", "World Bank GDP per Capita.csv")) %>%
  rename(country=`Country Name`) %>% 
  select(-`Indicator Name`, -`Indicator Code`, -`Country Code`) 
wb_gdp_pc$country <- countrycode(wb_gdp_pc$country, "country.name", "country.name")

wb_gdp_pc_final <- wb_gdp_pc %>% 
  pivot_longer(cols = 2:64,
               names_to = "year", 
               values_to = "gdp_per_capita") %>% 
  filter(country %in% iuu_index_countries) %>% 
  group_by(country) %>%
  fill(everything()) %>%  # Fill missing values within each country group
  slice(n()) %>%  # Keep only the last observation within each country group
  ungroup() %>%
  select(-year)
```


```{r}
### Fish production indicators
##### OK so this was cleaned and exported, I think that should happen in another file 
fish_id_wide <- read_csv(here("data", "fish_indicators.csv")) %>%
  clean_names()

fish_id_clean <- fish_id_wide %>% 
  filter(year >= filter_year) %>% 
  select(-country_code, -country_name) %>% 
  filter(country %in% iuu_index_countries)


fish_index_final <- fish_id_clean %>% 
  group_by(country) %>%
  fill(everything()) %>%  # Fill missing values within each country group
  slice(n()) %>%  # Keep only the last observation within each country group
  ungroup() %>%
  select(-year) %>% 
  #replace aquaculture NA values with 0
  mutate(aquaculture_production_metric_tons = replace(aquaculture_production_metric_tons, is.na(aquaculture_production_metric_tons), 0)) %>% 
  #replace total_fisheries_production NA values with capture_fisheries_production values
  mutate(total_fisheries_production_metric_tons = ifelse(is.na(total_fisheries_production_metric_tons), capture_fisheries_production_metric_tons, total_fisheries_production_metric_tons))
  

fish_index_final$aquaculture_production_metric_tons[fish_index_final$aquaculture_production_metric_tons == 0.000000e+00] <- .0000000000001
  

fish_index_final$ratio_capture <- fish_index_final$capture_fisheries_production_metric_tons/fish_index_final$aquaculture_production_metric_tons
  
```

### Skylight treatment logic
```{r}
# Create a data frame with NAs #renamed from common_countries_df
skylight_treatment_df <- data.frame(country = iuu_index_countries, iuu_index_countries = NA, active_skylight_countries = NA)

# Fill in values in the data frame based on the presence in vectors
skylight_treatment_df$iuu_index_countries[match(iuu_index_countries, skylight_treatment_df$country)] <- iuu_index_countries
skylight_treatment_df$active_skylight_countries[match(active_skylight_countries, skylight_treatment_df$country)] <- active_skylight_countries

skylight_treatment_df$skylight_treatment <- ifelse(is.na(skylight_treatment_df$active_skylight_countries), 0, 1)

skylight_treatment_df <- skylight_treatment_df %>% select(country, skylight_treatment)
```


### Compile skylight data
```{r}
ctk <- c("deal_title", "country", "deal_deployment_date", "deal_organisation","organization_type")

active_country_dates_df <- skylight_deal_dates %>% 
  subset(select = ctk) %>% 
  filter(deal_deployment_date > 2019) %>% 
  group_by(country) %>%
  filter(deal_deployment_date == min(deal_deployment_date, na.rm = TRUE)) %>%
  ungroup() %>%  #filter out duplicate country entries for country level analysis 
  distinct(country, deal_deployment_date, .keep_all = TRUE)

active_country_dates_clean <- active_country_dates_df %>% 
  mutate(treatment_year = as.integer(format(as.Date(deal_deployment_date), "%Y"))) %>% 
  filter(organization_type != "Regional") %>% #come back to this assumption later
  select(country, treatment_year) #%>% 
 # rename(deal_country = country)

# Combine all Skylight data into one df to use in final compilation
skylight_df_final <- skylight_treatment_df %>% 
  full_join(active_country_dates_clean, join_by(country)) %>% 
  full_join(weekly_country_engagements, join_by(country)) %>% 
  full_join(country_sessions, join_by(country))

skylight_df_final[is.na(skylight_df_final)] <- 0

skylight_df_final$skylight_treatment <- as.factor(skylight_df_final$skylight_treatment)
```


### Compile all datasets
```{r}
countries_to_exclude <- 
  c("Falkland Islands", "Pitcairn Islands", "Réunion", "Antarctica", "Cook Islands", "Taiwan", "North Korea") #excluded because they aren't in every dataset

all_index_df <- skylight_df_final %>% 
  full_join(wb_gov_index_final, join_by(country)) %>% 
  full_join(iuufr_index_final, join_by(country)) %>% 
  full_join(fish_index_final, join_by(country)) %>% 
  full_join(wb_gdp_pc_final, join_by(country)) %>% 
  filter(!country %in% countries_to_exclude) %>% 
  select(-treatment_year, -no_of_active_weeks, -sessions) %>% 
  clean_names() %>% 
  mutate_all(~ ifelse(is.na(.), mean(., na.rm = TRUE), .)) #replace all remaining NA values with the mean of the column 
  


final_na_counts <- as.data.frame(colSums(is.na(all_index_df)))
```

